### ISSUE TITLE
Plugins ordering: fix plugin should be run after warn plugin

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cli#153]
May be we can even find some performance enhancements

**Comment by petertrr** [comment]
Actually, with our current approach they are completely independent: they create their own copies of the files and operate on them. If we are talking about the combined mode (first - fix, then check unfixed warnings) - it's quite a large issue, that we haven't thoroughly considered yet.

**Comment by kgevorkyan** [comment]
@akuleshov7 I think this could be closed
