### ISSUE TITLE
Parsing exceptions during the parsing of invalid SARIF result 

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cli#388]
If the tool provides us invalid SARIF result and we fail on parsing of it - we know it definitely.

We need to handle that situation and NOT crush save-cli with exception. Instead - we need to catch an error and mark all tests in the batch **FAILED** with the reason in the debug info: `WE FAILED TO PARSE SARIF!!!111111 WOW, YOUR TOOL IS INVALID, CHECK THE GENERATION OF SARIF REPORT`.

**Comment by petertrr** [comment]
We also can put contents of the sarif file into debug info, but we should keep in mind that invalid file can cause invalid decoding into text or generally be too large.
