### ISSUE TITLE
SAVE-cli incorrectly uses inheritance

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cli#403]
When we run `./save warn-dir/chapter2` from `example/kotlin-diktat` directory, diktat fails with the following error:
`no exec_cmd in config`. It looks like the inheritance of configs is done incorrectly

**Comment by nulls** [comment]
The problem that we load `PluginConfig` only for current `TestConfig` and expect that parent already processed. Fixed it by adding a recursive processing of `TestConfig`

Also, found that we try to take `save.properties` only from a folder for first element of testsPath -- changed it to recursive 
 search up

**Comment by petertrr** [comment]
> but it depends on enabled mode in `save-cli`

IIRC, if `save.toml` contains `warn.wildCardInDirectoryMode` set to glob pattern, then we can process provided args as directories
