### ISSUE TITLE
test location should be relative to test root path

### ISSUE THREAD

**Issue by icemachined** [saveourtool/save-cli#412]
currently test location is set relative to tests root config 
but save-cloud rely on path relative to test root path which it send in cli parameters.
save cli should be in sync with incoming cli args and set file location relative to test root path.

**Comment by petertrr** [comment]
The change in #413 applies only to reporting. Is this about the issue when we run an execution on save-cloud with current test root deeper in hierarchy than the highest root and debug info is lost because of path parts missing?
