### ISSUE TITLE
Introduce `save-overrides.toml` 

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cli#435]
This file should contain following options:

- execCmd (or initially overrideExecCmd)
- execFlags (before https://github.com/saveourtool/save-cli/issues/434, later can be skipped)
- ~batchSeparator~
- ~batchSize~

As bonus - should be done separately later: 

`This file should support groups `[fix]` and `[warn]` to customize execution run for different type of plugins`

It allows to store such files in private repositories for test and provide them as external file for public tests.

_Originally posted by @nulls in https://github.com/saveourtool/save-cli/issues/430#issuecomment-1217718558_

**Comment by nulls** [comment]
Try to move `evaluatedToolConfig` to `Plugin`'s field level

**Comment by nulls** [comment]
> Need to add implementation of `com.saveourtool.save.core.utils.CmdExecutorBase` for `com.saveourtool.save.plugins.fix.FixPlugin`

Better to handle it in scope of https://github.com/saveourtool/save-cli/issues/434
