### ISSUE TITLE
Adapt FixPlugin for library for applying of SARIF fix patches

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cli#461]
We should be able to support comparison & applying fixes to files for tools, that have output in Sarif format with [Replacement object](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317889) section

**Comment by akuleshov7** [comment]
![image](https://user-images.githubusercontent.com/58667063/204279522-71ac6c86-b710-4e91-b2f3-afbfd29fd4b7.png)
