### ISSUE TITLE
TOML: Can't specify `tags` as a multi-line array

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cli#469]
According to the TOML specification, line breaks are OK when inside arrays, e.g.:

```toml
hosts = [
  "alpha",
  "omega"
]
```

Yet, when `save.toml` specifies the list of tags in the above way:

```toml
[general]
execCmd = "..."
suiteName = "..."
description = "..."
language = "..."
tags = [
"xxx"
]
```

&mdash; then `save-cli` just produces an output file of size **0** and doesn't run any tests:

```console
[DEBUG]: Using the following properties for SAVE execution: parallelMode=false, threads=1, logType=ALL, reportType=PLAIN, baseline=null, excludeSuites=null, includeSuites=null, language=null, resultOutput=FILE, reportDir=save-reports, testRootDir=., testFiles=[]
[DEBUG]: Created folders to save-reports\save.out
[DEBUG]: Created FILE to save-reports\save.out
[INFO]: Welcome to SAVE version 0.4.0-alpha.0.11+20221129T115851Z
[DEBUG]: Initializing reporter com.saveourtool.save.reporter.plain.PlainTextReporter of type PLAIN
[TRACE]: Discovering parent configs of save.toml
[DEBUG]: Processing test config from the toml file: save.toml
[TRACE]: Discovering all descendant `save.toml`s of save.toml
```

**Comment by kgevorkyan** [comment]
I guess it more related to `ktoml` https://github.com/akuleshov7/ktoml
As I see from its `README`, multiline arrays for now not supported

I think there is definitely should be some issue on this subject in `ktoml`, where we can check the progress

**Comment by 0x6675636b796f75676974687562** [comment]
@kgevorkyan, on `ktoml` side, there definitely is such an issue (akuleshov7/ktoml#126, to be implemented with akuleshov7/ktoml#166), but from the end-user perspective this is a problem with `save-cli`, not `ktoml`.

So let's keep this open until akuleshov7/ktoml#126 is fixed and a new version is released, so that we can upgrade.

**Comment by akuleshov7** [comment]
Merged, will release soon

**Comment by kgevorkyan** [comment]
@0x6675636b796f75676974687562, ktoml `0.4.0` has been released and we can probably close this

**Comment by 0x6675636b796f75676974687562** [comment]
> ktoml 0.4.0 has been released and we can probably close this

We definitely will, once #471 is landed.
