### ISSUE TITLE
SARIF: add support for relative paths with `uriBaseId`

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/save-cli#490]
Examples:

# A _relative_ URI holding a relative path

```json
"artifactLocation": {
                  "uri": "examples/Xss.js",
                  "uriBaseId": "%SRCROOT%",
                  "index": 0
                }
```

# An _absolute_ `file:` URI holding a relative path

```json
"artifactLocation": {
                  "uri": "file:examples/Xss.js",
                  "uriBaseId": "%SRCROOT%",
                  "index": 0
                }
```

**Comment by kgevorkyan** [comment]
Resolving of `uriBaseId` already supported in `sarif-utils` by `resolveUriBaseId` method. It also covered by tests

What about file protocol `file://`, such logic also considered in `sarif-utils` by  applying `dropFileProtocol` method, in curse of work of calculation the `uri`, probably some cases didn't considered by tests in `SarifUtilsTest.kt` from `sarif-utils`

**Comment by kgevorkyan** [comment]
What about `%20` it's definitely is not directly supported in `sarif-utils`. But may be it covered by `okio` in `toPath()` methods? Anyway, such cases should be tested

**Comment by 0x6675636b796f75676974687562** [comment]
Since `uriBaseId` is already supported, closing as implemented by @kgevorkyan.
